config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search', to: 'search#page'
  get 'users/profile'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # reason why its user and not users is because ever user account work for this
  get '/user_profile/:id', to: 'users#profile', as: 'user'
  # this is to targetmy comments too so i can go to posts/1/comment/1
  resources :posts do
    resources :comments
  end
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def page; end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/views/search/_form.html.erb
<%# Search form from ransack, q is the query , method make sure its getting and not creating or doing anything else%>
<%# d-flex is bootstrap styling %>
<%= search_form_for(@q, url: search_path, class:"d-flex") do |f| %>
  <%= f.search_field :title_or_action_text_rich_text_body_or_user_name_or_user_email_i_cont_any, placeholder: "Search For Novels..." , class: "search-bar"%>
  <div class="btn-search"> <%= f.submit "Search!", class: "btn btn-search" %> </div>
<% end %>

app/views/search/page.html.erb
  <section class="clean-block clean-post dark">
    <h1 class="text-center"><%= pluralize(@posts.count, " Result") %></h1>
    <div class="container">
      <div class="block-content">
        <div class="post-body">

<div class="container">
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%=sort_link(@q, :title, "Title", default_order: :asc) %></th>
      <th><%=sort_link(@q, :Description, "Novel Description") %></th>
      <th><%=sort_link(@q, :user_name, "Users") %></th>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do|post| %>
    <tr>
      <td><%=link_to post.title, post %></td>
      <td><%= post.Description.to_plain_text.truncate_words(15) %></td>
      <td><%=link_to post.user.name, user_path(post.user)%></td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>


        </div>
      </div>
    </div>
  </section>