config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search', to: 'search#page'
  get 'users/profile'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # reason why its user and not users is because ever user account work for this
  get '/user_profile/:id', to: 'users#profile', as: 'user'
  # this is to targetmy comments too so i can go to posts/1/comment/1
  resources :posts do
    resources :comments
  end
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  # needs the title and description to be filled in before submitting
  validates :title, presence: true
  validates :Description, presence: true
  has_rich_text :Description
  has_one :action_text_rich_text, class_name: 'ActionText::RichText', as: :record

  # post is by the user only belong to 1 user
  belongs_to :user

  # using destroy instead of delete so it removes the comments rather having floating comments
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  # authenticate the user to login before editing except the show and index html in posts
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :Description, :body)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.coun    t, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="margin-top: 2.5%">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div style="margin-top: 2.5%">
    <%= form.label :Description, style: "display: block" %>
    <%= form.rich_text_area :Description %>
  </div>

  <div style="margin-top: 2.5%">
    <%= form.submit "update", class:"btn btn-primary" %>
    <%= link_to "Back to posts", posts_path,class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="block-content">
  <div class="clean-novel-post">
    <div class="row">
      <div class="col-lg-7">
        <h2>Novel Title:<br></h2>
        <h3><%= post.title %></h3>
        <div class="info"><span class="text-muted">Posted <%= time_ago_in_words(post.created_at) %> ago by <a> <%= link_to post.user.name, user_path(post.user) %></a></span></div>
        <p><%= post.Description %></p>
      </div>
      <div class="novel-buttons"><button class="btn novel-buttons" type="button"> <%= link_to "Show this post", post ,  class:"nav-link active"%> </button></div>
    </div>
  </div>
</div>

app/views/posts/_post_styling.html.erb
<main class="page novel-post-list">
  <section class="clean-block clean-novel-list dark">
    <div class="container">
      <div class="block-heading"><br>
        <h2 class="text-info">Novel Post List</h2>
        <p> Read other peoples novels and comment on what you think. explore and enjoy other peoples story</p>
      </div>
      <div id="posts">
        <% @posts.each do |post| %>
          <%= render post %>
          <div class="break-posts"></div>
        <% end %>
      </div>
    </div>
    </div>
  </section>
</main>

app/views/posts/edit.html.erb
<section class="clean-block clean-form dark">
  <div class="container">
    <div class="block-heading">
      <div class="clean-novel-post">
        <h2 class="text-info">Edit Your Novel</h2>
        <p>Edit your story, its your world your free range of your own imagination</p>
      </div>
    </div>

        <%= render "form", post: @post %>
  </div>
</section>

app/views/posts/index.html.erb
<div class="post">
<%= render "post_styling"%>
</div>

app/views/posts/new.html.erb
<section class="clean-block clean-form dark">
  <div class="container">
    <div class="block-heading">

      <div class="clean-novel-post">
        <h2 class="text-info">Post Your Novel</h2>
        <p>Share your ideas and post them here. See what others think about your story</p>
      </div>
      </div>
      <div class="block-content">
          <%= render "form", post: @post, class: "block-content" %>
      </div>
  </div>
</section>

app/views/posts/show.html.erb
<main class="page novel-post">
  <section class="clean-block clean-post dark">
    <div class="container">
      <div class="block-content">
        <div class="post-body">

          <div class="block-content">
            <div class="clean-novel-post">
          <h2>Novel Title:<br></h2>
          <h3><%= @post.title %></h3>
          <div class="info">Posted <%= time_ago_in_words(@post.created_at) %> ago by <%= link_to @post.user.name, user_path(@post.user) %>
          <p><%= @post.Description %></p>
          </div>
        <%if @post.user == current_user %>

            <%= link_to "Edit this post", edit_post_path(@post),class:"btn btn-primary" %>
            <%= button_to "Destroy this post", @post, method: :delete, class:"btn btn-danger" %> <br>
        <% end %>
        <%= link_to "Back to posts", posts_path,class:"btn btn-secondary" %><hr>
          <%= render "comments/form", post: @post%>

          <% @comments.each do|comment| %>
            <%= render "comments/comment", post: @post, comment: comment%>
          <% end %>
      </div>
      </div>
   <div class="container">


   </div>

    </div>
    </div>
    </div>
  </section>
</main>