config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search', to: 'search#page'
  get 'users/profile'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # reason why its user and not users is because ever user account work for this
  get '/user_profile/:id', to: 'users#profile', as: 'user'
  # this is to targetmy comments too so i can go to posts/1/comment/1
  resources :posts do
    resources :comments
  end
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  # needs the title and description to be filled in before submitting
  validates :title, presence: true
  validates :Description, presence: true
  has_rich_text :Description
  has_one :action_text_rich_text, class_name: 'ActionText::RichText', as: :record

  # post is by the user only belong to 1 user
  belongs_to :user

  # using destroy instead of delete so it removes the comments rather having floating comments
  has_many :comments, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # user will have more than 1 post
  has_many :posts, dependent: :destroy

  # delete comments too
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_query

  def set_query
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = 'comment was created'
    else
      flash[:alert] = 'comment was not created'
    end
    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end

  def about; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  # authenticate the user to login before editing except the show and index html in posts
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :Description, :body)
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def page; end
end

app/controllers/turbo_devise_controller.rb
# frozen_string_literal: true

# app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      has_errors? && default_action
      render rendering_options.merge(formats: :html, status: :unprocessable_entity)
    else
      redirect_to navigation_location
    end
  end
  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user

  def profile; end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
    <%elsif alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

<nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar">

  <div class="container"><%= link_to "NovelR", root_path,class: "navbar-brand logo" %>

    <% if current_user %>
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.name %>
      </a>
      <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDropdown">
        <li><%= link_to "Edit Account",edit_user_registration_path, class:"dropdown-item"%></li>
        <li><%= link_to "Post Novel", new_post_path,class:"dropdown-item" %></li>
        <li><%= link_to "View Novels", posts_path,class:"dropdown-item" %></li>
        <li><hr class="dropdown-divider"></li>
        <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"dropdown-item"%></li>
      </ul>
    <% else %>
      <ul class="navbar-nav ms-auto">
      <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class:"nav-link active" %></li>
      <li class="nav-item"> <%= link_to "Login", new_user_session_path, class:"nav-link active" %></li>
      </ul>
    <% end %>

    <div class="collapse navbar-collapse" id="navcol-1">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item"><%= link_to "Home", root_path, class:"nav-link active" %></li>
        <li class="nav-item"><%= link_to "Post Novels", new_post_path, class:"nav-link active" %></li>
        <li class="nav-item"><%= link_to "View Novels", posts_path, class:"nav-link active" %></li>
      </ul>
    </div>
  </div>
  <div class ="render_search"><%=render "search/form" %></div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Novel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# bootstrap from the website %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
      <header>
        <%# render loads from _the name this makes code neater %>
        <%= render "layouts/navbar" %>
        <%= render "layouts/alerts" %>
      </header>
    <main>
      <%= yield %>
    </main>

      <!--footer at the bottom as a decor and for watermark copyright-->
      <footer class="page-footer dark" style="padding-top: 8px;padding-bottom: 0px;margin-bottom: 0px;">
        <div class="footer-copyright"></div>
      </footer>










  </body>

</html>

app/views/pages/_topnovel.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6 col-lg-4">
    <div class="card text-center clean-card"><img class="card-img-top w-100 d-block" src=<%= asset_path 'home/book1.jpg' %>>
      <div class="card-body info">
        <h4 class="card-title"> Chris Whitaker </h4>
        <p class="card-text">Chris Whitaker is the award-winning author of Tall Oaks and All The Wicked Girls. Both books were published to widespread critical acclaim, with Tall Oaks going on to win the CWA John Creasey New Blood Dagger Award. This is a beautifully written mystery, packed with unforgettable characters.Buy the book now to enjoy</p>
        <%= button_to "Buy Now","https://www.amazon.co.uk/Begin-End-beautifully-unforgettable-characters/dp/1785769405/ref=sr_1_4?crid=22AL5K12KICM1&keywords=novel&qid=1669903439&sprefix=novel%2Caps%2C87&sr=8-43", method: :get, class:"btn btn-outline-primary btn-lg" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-lg-4">
    <div class="card text-center clean-card"><img class="card-img-top w-100 d-block" src=<%= asset_path 'home/book2.jpg' %>>
      <div class="card-body info">
        <h4 class="card-title"> Donal Ryan </h4>
        <p class="card-text">Donal Ryan is an Irish writer. He has published six novels and one short story collection. In 2016, novelist and playwright Sebastian Barry described Ryan in The Guardian newspaper as "the king of the new wave of Irish writers". All of his novels have been number one bestsellers in Ireland. </p>
        <%= button_to "Buy Now","https://www.easons.com/Queen-Of-Dirt-Island-Donal-Ryan-9781781620403", method: :get, class:"btn btn-outline-primary btn-lg" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-lg-4">
    <div class="card text-center clean-card"><img class="card-img-top w-100 d-block"src=<%= asset_path 'home/book3.jpg' %>>
      <div class="card-body info">
        <h4 class="card-title">Mei Hachimoku</h4>
        <p class="card-text">A manga and light novel publisher. Seven Seas is devoted to producing high quality manga, comics, & novels with great stories and art! The award-winning, bittersweet sci-fi tale of a mysterious tunnel, time travel, and young summer love by the creators of Wait For Me Yesterday in Spring–inspired an anime film! Buy now to enjoy this story </p>
        <%= button_to "Buy Now","https://www.easons.com/the-tunnel-to-summer-the-exit-of-goodbyes-light-novel-mei-hachimoku-9781638584155", method: :get, class:"btn btn-outline-primary btn-lg" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="container">
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<%= link_to "Home", root_path, class:"btn btn-secondary" %>
<%= link_to "Posts Novels", posts_path, class:"btn btn-primary"%>
</div>

app/views/pages/home.html.erb
<!-- Site was made using the app Bootstrap Studio Applied for the student version to create a website with bootstrap -->

<body>
 <div class="navbar"><%= render "layouts/navbar" %></div>
<main class="page landing-page">
  <section class="clean-block clean-hero" style="background-image: url(<%= asset_path 'home/imagedesk.jpg' %>);color: #f5deb3a6;">
    <div class="text">
      <h2>Welcome To NovelR</h2>
      <p>Find All the newest released Novels made by talented starter individuals. Read about there stories and comment&nbsp;</p>
      <%= button_to "View Novels", posts_path, method: :get, class:"btn btn-outline-light btn-lg" %>
    </div>
  </section>


  <section class="clean-block clean-info dark">
    <div class="container">
      <div class="block-heading">
        <h2 class="text-info">Info</h2>
        <p>Want to be a creator also? Publish your own novels and see what others think. Share the story of your imagination</p>
      </div>
      <div class="row align-items-center">
        <div class="col-md-6"><img class="img-thumbnail" src=<%= asset_path 'home/novels.jpg' %>></div>
        <div class="col-md-6">
          <h3>Many creators for publication</h3>
          <div class="getting-started-info">
            <p>Many creators that upload there novels also have a chance for there novels to be published worldwide. Buy some of there works now to support them</p>
          </div>
          <%= button_to "Buy Now","https://www.easons.com/custom-catalog/top_100_books?gclid=Cj0KCQiAvqGcBhCJARIsAFQ5ke4gZRuX9Wx-4CmVqHRDOdETFosfaohS9nvbFn8oWU-ZIEKY4ViViIsaAr6oEALw_wcB", method: :get, class:"btn btn-outline-primary btn-lg" %>
        </div>
      </div>
    </div>
  </section>


  <section class="clean-block features">
    <div class="container">
      <div class="block-heading">
        <h2 class="text-info">Popular Light Novels</h2>
        <p> Some popular authors and rankings can be seen here. From small creators to very popular creators today</p>
      </div>
      <div class="row justify-content-center">
        <div class="col-md-5 feature-box">
          <!-- Twitter embeded link for external source of data-->
          <a class="twitter-timeline" data-lang="en" data-width="500" data-height="500" data-theme="light" href="https://twitter.com/Erzat110?ref_src=twsrc%5Etfw">Tweets by Erzat110</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
    </div>
    </div>
  </section>


  <section class="clean-block slider dark">
    <div class="container">
      <div class="block-heading">
        <h2 class="text-info">Novel Authors</h2>
        <p>Here are some novels that you may like. These are some talented authors who have won awards and have published some novels</p>
      </div>
    <%=render "topnovel" %>
    </div>
  </section>


  <section class="clean-block about-us">
    <div class="container">
      <div class="block-heading">
        <h2 class="text-info">About NovelR</h2>
        <p>NovelR was created using Ruby on rails as the framework. Bootstrap studio was used to create the html and css of the website. This site was made by Joswel,x19369011</p>
      </div>
    </div>
  </section>

</main>


</body>